require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
-- require "user.cmp"
-- require "user.lsp"
-- require "user.telescope"
-- require "user.neoclip"
-- require "user.treesitter"
require "user.autopairs"
require "user.comment"
-- require "user.gitsigns"
require "user.nvim-tree"
-- require "user.bufferline"
require "user.lualine"
-- require "user.toggleterm"
-- require "user.project"
-- require "user.impatient"
-- require "user.indentline"
-- require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.harpoon"
require "user.hop"
require "user.leap"
require "user.quickscope"
require "user.nvim-hlslens"
require "user.im-select"
-- require "user.vim-test"
-- require "user.vim-ultest"
-- require "user.nvim-dap"
-- require "user.asyncrun"
-- require "user.git-worktree"
-- require "user.nvim-gps"
-- require "user.refactoring"
-- require "user.illuminate"
