require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"

-- -- added by gh below
require "user.harpoon"
require "user.hop"
require "user.leap"
require "user.quickscope"
require "user.im-select"
require "user.chatgpt"
require "user.betterescape"
require "user.nvim-gps"
require "user.nvim-hlslens"
-- require "user.neoclip"
-- require "user.asyncrun"

